[project]
name = "google-adk-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.1"
dependencies = [
    "google-adk>=1.5.0",
    "litellm>=1.73.6",
]
